NHA:
  docker_image: nha
  container: nha_server
  db_container: nha_db
  db: nha_data
  db_user: nha_user

CIDQ:
  docker_image: cidq
  container: cidq_server
  db_container: cidq_db
  db: cidq_data
  db_user: cidq_user
  runtests: ~/source/brightlink/runtests.sh

NASM:
  docker_image: nasm
  container: nasm_server
  db_container: nasm_db
  db: nasm_data
  db_user: nasm_user
  runtests: ~/source/brightlink/runtests.sh

test:
  db_container: test_db

whitefield:
  container: whitefield
  db_container: whitefield
  db_user: whitefield
  db: whitefield
  runtests: ~/source/whitefield/runtests.sh
